name: SelfHostedRunnerWorkflowDemo1

on:
  push:
    branches:
      - main
  
  workflow_dispatch:
    inputs:
      test-level:
        description: Test-level for apex test run
        type: choice
        default: RunLocalTests
        options:
          - RunLocalTests
          - RunAllTestsInOrg

  pull_request:
    types:
      - opened
      - synchronize
      - closed

jobs:
  Validate:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Echo some random stuff  
        run: |
          echo This is running on self hosted runner
          command -v sf 
          sf --version
          whoami
          git status
          git branch
          echo ${{github.event.inputs.test-level || 'Default value'}}
          echo ${{github.actor}}}
          echo ${{github.event_name}}